name: actions workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          echo "*************pwd --- ls *************"
          pwd ls
      - name: simple js actions
        id: abcd
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Suresh Musale
      - name: log greeting time
        run: echo {{  steps.abcd.outputs.time }}
