name: actions workflow
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          echo "before checkout"
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{gitHub.token}}
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          echo "after checkout"
          pwd
          ls -a
      - name: simple js actions
        id: abcd
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Suresh Musale
      - name: log greeting time
        run: echo {{  steps.abcd.outputs.time }}