name: Shell commands


on: [push]

jobs:
  first-job-run-shell-command:
    runs-on: ubuntu-latest
    steps:
    - name: echo a string
      run: echo "hello GitHub Actions"
    - name: multi line script
      run: |
        echo "----- printing platform processor"
        node -v
        npm -v
    - name: python commands
      #run: echo "printing platform processor"
      #name: print processor
      run: |
        import platform
        print(platform.processor())
      shell: python
  run-second-job-print-windows:
    runs-on: windows-latest
    steps:
      - name: directory powershell
        run: Get-Location
      - name: directory bash
        run: pwd
        shell: bash