name: Shell commands


on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
    - name: echo a string
      run: echo "hello GitHub Actions"
    - name: multi line script
      run: |
        node -v
        npm -v
    - name: python commands
      #run: echo "printing platform processor"
      #name: print processor
      run: |
        echo "----- printing platform processor"
        import platform
        print(platform.processor())
      shell: python
           