name: Shell commands


on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
    - name: echo a string
      run: eecho "hello GitHub Actions"
    - name: multi line script
      run: |
        node -v
        npm -v



